### PR TITLE
Properly handle FieldAttribute.default if callable

### LINKED ISSUE #48673: Traceback when using omit on play keywords
##### SUMMARY
Recently updated my Fedora 28 to Fedora 29, so I'm now using Ansible 2.7.1 with 3.7.1

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
core

##### ANSIBLE VERSION

```
ansible 2.7.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/echampetier/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.1 (default, Nov  5 2018, 14:07:04) [GCC 8.2.1 20181011 (Red Hat 8.2.1-4)]
```

##### CONFIGURATION

```
no output
```

##### OS / ENVIRONMENT
Running Ansible on Fedora 29, target doesn't matter

##### STEPS TO REPRODUCE
Here a minimal not working test case that was working on Fedora 28 (maybe ansible 2.6.5-1.fc28 but not sure)
```yaml
- hosts: all
  any_errors_fatal: true
  serial: "{{ ansible_serial | default(omit) }}"
  tasks:
  - name: just ping
    ping:
```

##### EXPECTED RESULTS
It works

##### ACTUAL RESULTS

```
[echampetier@echampetier ansiblebug]$ ansible-playbook -i inventory-test playbook-test.yml -vvvv
ansible-playbook 2.7.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/echampetier/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 3.7.1 (default, Nov  5 2018, 14:07:04) [GCC 8.2.1 20181011 (Red Hat 8.2.1-4)]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
/home/echampetier/ansiblebug/inventory-test did not meet host_list requirements, check plugin documentation if this is unexpected
/home/echampetier/ansiblebug/inventory-test did not meet script requirements, check plugin documentation if this is unexpected
Parsed /home/echampetier/ansiblebug/inventory-test inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python3.7/site-packages/ansible/plugins/callback/default.py

PLAYBOOK: playbook-test.yml ***************************************************************************************************************************************************************************************
1 plays in playbook-test.yml
ERROR! Unexpected Exception, this is probably a bug: object of type 'type' has no len()
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 118, in <module>
    exit_code = cli.run()
  File "/usr/lib/python3.7/site-packages/ansible/cli/playbook.py", line 122, in run
    results = pbex.run()
  File "/usr/lib/python3.7/site-packages/ansible/executor/playbook_executor.py", line 148, in run
    batches = self._get_serialized_batches(play)
  File "/usr/lib/python3.7/site-packages/ansible/executor/playbook_executor.py", line 243, in _get_serialized_batches
    if len(serial_batch_list) == 0:
TypeError: object of type 'type' has no len()
```

### PR DESCRIPTION
**Pull request by mkrizek**
##### SUMMARY

Fixes #48673

Since https://github.com/ansible/ansible/pull/46833, `attribute.default` would be in the case of #48673 now `list`, as opposed to `[]` previously, which results in `exception TypeError: object of type 'type' has no len()`

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

lib/ansible/playbook/base.py

### CODE REVIEW

**Comment by sivel** [comment]
Can you add a simple integration test for this too?

A change log as well.

**Comment by mkrizek** [comment]
Sigh, I tend to forget to add a changelog too often...

Both added now.

File: test/integration/targets/omit/runme.sh [hunk 1]
```diff
@@ -0,0 +1,5 @@
+#!/usr/bin/env bash
```
Comment (sivel) [inline test/integration/targets/omit/runme.sh:1]: Not a blocker, but if you make the `omit` target a role (`test/integration/targets/omit/tasks/main.yml`), then you don't need an explicit `runme.sh`

Comment (mkrizek) [reply test/integration/targets/omit/runme.sh:1]: But that way I can't specify play keywords, no?

Comment (sivel) [reply test/integration/targets/omit/runme.sh:1]: doh. Ignore me.

**Review by sivel — APPROVED** [review]
