### PR TITLE
ansible-test - generate dist_info

### LINKED ISSUE #86695: cannot find `importlib.metadata` for `ansible-core` inside `ansible-test` for newer ansible versions
### Summary

In newer versions of `ansible-test`, `pip show ansible-core` fails and `pip freeze` does not contain `ansible-core`.

### Issue Type

Bug Report

### Component Name

ansible-test

### Ansible Version

works in `ansible-core==2.17`, doesn't work in `ansible-core==2.18 ansible-core==2.19`

### Configuration

```console
no configuration
```

### OS / Environment

github actions

### Steps to Reproduce

I can reproduce with github actions. I made a [minimal repo](https://github.com/simonLeary42/ansible-test-gh-action-test):

```console
$ find . -type f ! -path './.git/*' ! -path 'galaxy.yml' | xargs batcat
───────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: ./tests/integration/targets/foobar/runme.sh
───────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ #!/usr/bin/env bash
   2   │ set -x
   3   │ env; python -c 'from importlib.metadata import version; print(version("ansible-core"));'
───────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
───────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: ./.github/workflows/test.yml
───────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ name: test
   2   │ on: [push]
   3   │ jobs:
   4   │   ansible-test:
   5   │     runs-on: ubuntu-latest
   6   │     steps:
   7   │       - name: test
   8   │         uses: ansible-community/ansible-test-gh-action@d3a8ec7a59694e25e210fcd44738910149537f0e
   9   │         with:
  10   │           ansible-core-version: ${{ matrix.ansible-core-version }}
  11   │           testing-type: integration
  12   │           target: foobar
  13   │           pre-test-cmd: env; python -c 'from importlib.metadata import version; print(version("ansible-core"));'
  14   │     strategy:
  15   │       matrix:
  16   │         ansible-core-version: [stable-2.17, stable-2.18]
  17   │       fail-fast: false
───────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

I haven't been able to reproduce on my own machine. I can find the metadata within `ansible-test` using both `ansible-core` versions 2.17 and 2.18:

<details>

```console
$ uv venv /tmp/ansible-test-2.17 --python=3.12
Using CPython 3.12.13 interpreter at: /opt/homebrew/opt/python@3.12/bin/python3.12
Creating virtual environment at: /tmp/ansible-test-2.17
Activate with: source /tmp/ansible-test-2.17/bin/activate
$ uv pip install --python=/tmp/ansible-test-2.17/bin/python ansible-core==2.17 ansible
Using Python 3.12.13 environment at: /private/tmp/ansible-test-2.17
Resolved 10 packages in 47ms
Prepared 3 packages in 34ms
Installed 10 packages in 219ms
 + ansible==10.0.1
 + ansible-core==2.17.0
 + cffi==2.0.0
 + cryptography==46.0.5
 + jinja2==3.1.6
 + markupsafe==3.0.3
 + packaging==26.0
 + pycparser==3.0
 + pyyaml==6.0.3
 + resolvelib==1.0.1
$ uv venv /tmp/ansible-test-2.18 --python=3.13
Using CPython 3.13.12 interpreter at: /opt/homebrew/opt/python@3.13/bin/python3.13
Creating virtual environment at: /tmp/ansible-test-2.18
Activate with: source /tmp/ansible-test-2.18/bin/activate
$ uv pip install --python=/tmp/ansible-test-2.18/bin/python ansible-core==2.18.15rc1 ansible
Using Python 3.13.12 environment at: /private/tmp/ansible-test-2.18
Resolved 10 packages in 153ms
Prepared 5 packages in 2.98s
Installed 10 packages in 265ms
 + ansible==11.13.0
 + ansible-core==2.18.15rc1
 + cffi==2.0.0
 + cryptography==46.0.5
 + jinja2==3.1.6
 + markupsafe==3.0.3
 + packaging==26.0
 + pycparser==3.0
 + pyyaml==6.0.3
 + resolvelib==1.0.1
$ /tmp/ansible-test-2.17/bin/ansible-test integration
WARNING: Unable to determine context for the following test targets, they will be run on the target host: foobar
Running foobar integration test script
+ env
...
+ python -c 'from importlib.metadata import version; print(version("ansible-core"));'
2.17.0
WARNING: Reviewing previous 1 warning(s):
WARNING: Unable to determine context for the following test targets, they will be run on the target host: foobar
$ /tmp/ansible-test-2.18/bin/ansible-test integration
WARNING: Unable to determine context for the following test targets, they will be run on the target host: foobar
Running foobar integration test script
+ env
...
+ python -c 'from importlib.metadata import version; print(version("ansible-core"));'
2.18.0
WARNING: Reviewing previous 1 warning(s):
WARNING: Unable to determine context for the following test targets, they will be run on the target host: foobar
```

</details>

### Expected Results

When using `ansible-core-version` `stable-2.17`, [I can always find the package metadata](https://github.com/simonLeary42/ansible-test-gh-action-test/actions/runs/23313295401/job/67806020168#step:3:958).

### Actual Results

When using `ansible-core-version` `stable-2.18`, [I cannot find the package metadata inside `ansible-test`](https://github.com/simonLeary42/ansible-test-gh-action-test/actions/runs/23313295401/job/67806020156#step:3:979), but [I can outside, when the `pre-test-cmd` is run](https://github.com/simonLeary42/ansible-test-gh-action-test/actions/runs/23313295401/job/67806020156#step:3:735).

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct

### PR DESCRIPTION
**Pull request by sivel**
##### SUMMARY

ansible-test - generate dist_info. Fixes #86695

##### ISSUE TYPE

- Bugfix Pull Request

### CODE REVIEW

File: test/integration/targets/ansible-test-metadata/runme.sh [hunk 1]
```diff
@@ -0,0 +1,7 @@
+#!/usr/bin/env bash
+# Verify that importlib.metadata can find ansible-core using the PYTHONPATH set by ansible-test.
+# Regression test for https://github.com/ansible/ansible/issues/86695
+
+set -eux
+
+python -c "from importlib.metadata import version; print(version('ansible-core'))"
```
Comment (mattclay) [inline test/integration/targets/ansible-test-metadata/runme.sh]: It would be good to verify the version is as expected.

Comment (sivel) [reply test/integration/targets/ansible-test-metadata/runme.sh]: Done. I added another integration env var called `ANSIBLE_VERSION` that ansible-test exposes, just to be explicit for the version comparison,

File: test/lib/ansible_test/_internal/ansible_util.py [hunk 2]
```diff
@@ -274,11 +276,30 @@ def get_ansible_python_path(args: CommonConfig) -> str:
 
         os.symlink(ANSIBLE_LIB_ROOT, os.path.join(python_path, 'ansible'))
 
+    if not args.explain:
+        generate_dist_info(python_path)
```
Comment (mattclay) [inline test/lib/ansible_test/_internal/ansible_util.py:281]: I'm wondering if we should be cleaning up dist-info directories from other versions. If we don't, they're going to keep accumulating locally when not using delegation.

Also, there's no git ignore for these directories, so they're showing up as untracked files.

Comment (sivel) [reply test/lib/ansible_test/_internal/ansible_util.py:281]: Hm, I can probably do that.  I tend to never run tests outside of docker, so I didn't see they were sticking around.

Comment (sivel) [reply test/lib/ansible_test/_internal/ansible_util.py:281]: Done.

File: test/lib/ansible_test/_internal/ansible_util.py [hunk 3]
```diff
@@ -274,11 +277,33 @@ def get_ansible_python_path(args: CommonConfig) -> str:
...
+Name: ansible-core
+Version: {version}
+'''
+    for dist_info in pathlib.Path(path).glob('ansible_core-*.dist-info'):
+        shutil.rmtree(dist_info, ignore_errors=True)
+
+    metadata_path = os.path.join(path, f'ansible_core-{version}.dist-info', 'METADATA')
+
+    if os.path.exists(metadata_path):
+        return
```
Comment (mattclay) [inline test/lib/ansible_test/_internal/ansible_util.py]: Isn't this branch unreachable now that we're removing all the directories up front?

Comment (sivel) [reply test/lib/ansible_test/_internal/ansible_util.py]: This what I get for moving too fast. Something else is going on in the PR too. I'll investigate.

File: .gitignore [hunk 4]
```diff
@@ -94,6 +94,8 @@ Vagrantfile
 /lib/ansible_core.egg-info/
 # First used in the `devel` branch during Ansible 2.18 development.
 /ansible_core.egg-info/
+# First used in the `devel` branch during Ansible 2.21 development.
+lib/ansible_core-*.dist-info/
```
Comment (mattclay) [inline .gitignore:98]: This PR should probably be backported once merged. For any maintained branches that don't see a backport, we should at least add this ignore to keep them from showing up when switching to older branches while doing local development and testing.

Comment (sivel) [reply .gitignore:98]: I planned to backport to 2.18. That would just leave 2.16 without the `.gitignore`, which could be backported separately if necessary.

File: test/lib/ansible_test/_internal/ansible_util.py (hunk 3 above)
Comment (sivel) [reply test/lib/ansible_test/_internal/ansible_util.py]: Ok, this should all be resolved. I forgot why I added `'''\` and removed the backslash in another commit. I've restored it, and resolved the unreachable branch issue.

**Review by mattclay — APPROVED** [review]
