### PR TITLE
Fix ansible.builtin.include_vars - depth

### LINKED ISSUE #80987: ansible.builtin.include_vars - depth doesn't work as described
### Summary

Not all var files which are located in the specified depth of a "dir" are included.

### Issue Type

Bug Report

### Component Name

ansible.builtin.include_vars

### Ansible Version

```console
$ ansible --version
ansible [core 2.14.6]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/kpog/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/kpog/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
CONFIG_FILE() = /etc/ansible/ansible.cfg
```

### OS / Environment

Ubuntu22.04 - desktop

### Steps to Reproduce

```yaml (paste below)
- name: Include vars example
  hosts: localhost

  tasks:
    - name: Include all yml configuration files from folder "{{ my_config_folder }}"
      vars:
        my_config_folder: "/home/kpog/WORK/TMP/include_vars/config"
      ansible.builtin.include_vars:
        dir: "{{ my_config_folder }}"
        extensions:
          - 'yml'
          - 'yaml'
        ignore_unknown_extensions: 'yes'
        depth: 2
        name: my_include_vars

    - name: Print included params
      debug:
        var: my_include_vars

```

### Expected Results

Config folder structure:
```
config
├── config0.yml
├── sub1
│   ├── config1.yml
│   └── sub11
│       ├── config11.yml
│       └── sub111
│           └── config111.yml
├── sub2
│   ├── config2.yml
│   └── sub21
│       ├── config21.yml
│       └── sub211
│           └── config211.yml
└── sub3
    └── config3.yml
```
On each configX.yml there is one parameter my_varX: "{{ folder of the file }}"

When using for example depth: "2" the config files:
config0.yml
config1.yml
config2.yml
config3.yml
should be included.

### Actual Results

```console
When using depth: "0" all configX.yml files are included. Result of playbook is:

ASK [Print included params] *******************************************************************************************************************************
ok: [localhost] => {
    "my_include_vars": {
        "my_name0": "config/config0.yml",
        "my_name1": "config/sub1/config1.yml",
        "my_name11": "config/sub1/sub11/config11.yml",
        "my_name111": "config/sub1/sub11/sub111/config111.yml",
        "my_name2": "config/sub2/config2.yml",
        "my_name21": "config/sub2/sub21/config21.yml",
        "my_name211": "config/sub2/sub21/sub211/config211.yml",
        "my_name3": "config/sub3/config3.yml"
    }
}

When using depth: "2" only config0.yml and config1.yml are included, but not config2.yml and config3.yml Result of playbook is:
TASK [Print included params] *******************************************************************************************************************************
ok: [localhost] => {
    "my_include_vars": {
        "my_name0": "config/config0.yml",
        "my_name1": "config/sub1/config1.yml"
    }
}


When using depth: "6" result of playbook is:
TASK [Print included params] *******************************************************************************************************************************
ok: [localhost] => {
    "my_include_vars": {
        "my_name0": "config/config0.yml",
        "my_name1": "config/sub1/config1.yml",
        "my_name11": "config/sub1/sub11/config11.yml",
        "my_name111": "config/sub1/sub11/sub111/config111.yml",
        "my_name2": "config/sub2/config2.yml",
        "my_name21": "config/sub2/sub21/config21.yml"
    }
}

It seems that count counter is just always incremented for the each subfolder and doesn't take account of an actual folder structure.
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

### PR DESCRIPTION
**Pull request by tachyontec**
##### SUMMARY

Changed vars.py, so it starts from depth 1 as root, as suggested by @sivel 

Fixes #80987 

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

vars.py

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Review by jborean93 — DISMISSED** [review]
Would you be able to add a test for this scenario to avoid any future regressions. It also requires a changelog fragment to document this bugfix https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment.

**Comment by tachyontec** [comment]
Tests passed, I think we are ready to merge ;)

File: test/integration/targets/include_vars-ad-hoc/runme.sh [hunk 1]
```diff
@@ -4,3 +4,21 @@ set -eux
 
 ansible testhost -i ../../inventory -m include_vars -a 'dir/inc.yml' "$@"
 ansible testhost -i ../../inventory -m include_vars -a 'dir=dir' "$@"
+
+ansible-playbook playbook.yml>output.txt
```
Comment (s-hertel) [inline test/integration/targets/include_vars-ad-hoc/runme.sh]: This should go in the normal include_vars test suite since it's not testing something adhoc specific (and is not using adhoc). Rather than grepping for defined variables, you could do this in the test play with an assert task. Other than that, LGTM.
