### PR TITLE
Fix ctrl+c in pause module and make other improvements

### LINKED ISSUE #35372: pause module no longer allows abort
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

pause

##### ANSIBLE VERSION
`ansible --version`:

```
ansible 2.5.0 (devel 90f0c411e4) last updated 2018/01/20 04:59:06 (GMT +000)
  config file = /Users/jcuzella/src/pub/ansible-pause-bug-reproduction/ansible.cfg
  configured module search path = [u'/Users/jcuzella/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/ansible/ansible/lib/ansible
  executable location = /opt/ansible/ansible/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION

Results of `ansible-config dump --only-changed`:

```
[DEPRECATION WARNING]: DEFAULT_SUDO_FLAGS option, In favor of become which is a generic framework , use become instead. This feature will be removed in version 2.8. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: ANSIBLE_HOSTS option, The variable is misleading as it can be a list of hosts and/or paths to inventory sources , use ANSIBLE_INVENTORY instead. This feature will be removed in version 2.8. Deprecation warnings
can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: DEFAULT_SUDO_EXE option, In favor of become which is a generic framework , use become instead. This feature will be removed in version 2.8. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: DEFAULT_SUDO_USER option, In favor of become which is a generic framework , use become instead. This feature will be removed in version 2.8. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
ANSIBLE_SSH_ARGS(env: ANSIBLE_SSH_ARGS) =  -o ForwardAgent=yes -o ControlPath=/tmp/ssh-%r@%h:%p -o ControlMaster=auto -o ControlPersist=60s
DEFAULT_ACTION_PLUGIN_PATH(/Users/jcuzella/src/pub/ansible-pause-bug-reproduction/ansible.cfg) = [u'/usr/share/ansible_plugins/action_plugins']
DEFAULT_CALLBACK_PLUGIN_PATH(/Users/jcuzella/src/pub/ansible-pause-bug-reproduction/ansible.cfg) = [u'/usr/share/ansible_plugins/callback_plugins']
DEFAULT_CONNECTION_PLUGIN_PATH(/Users/jcuzella/src/pub/ansible-pause-bug-reproduction/ansible.cfg) = [u'/usr/share/ansible_plugins/connection_plugins']
DEFAULT_FILTER_PLUGIN_PATH(/Users/jcuzella/src/pub/ansible-pause-bug-reproduction/ansible.cfg) = [u'/Users/jcuzella/src/pub/ansible-pause-bug-reproduction/filter_plugins']
DEFAULT_FORKS(/Users/jcuzella/src/pub/ansible-pause-bug-reproduction/ansible.cfg) = 5
DEFAULT_HOST_LIST(env: ANSIBLE_HOSTS) = [u'/Users/jcuzella/src/pub/ansible-pause-bug-reproduction/inventory']
DEFAULT_LOOKUP_PLUGIN_PATH(/Users/jcuzella/src/pub/ansible-pause-bug-reproduction/ansible.cfg) = [u'/usr/share/ansible_plugins/lookup_plugins']
DEFAULT_MANAGED_STR(/Users/jcuzella/src/pub/ansible-pause-bug-reproduction/ansible.cfg) = This file is managed by Ansible, all changes will be lost.
DEFAULT_POLL_INTERVAL(/Users/jcuzella/src/pub/ansible-pause-bug-reproduction/ansible.cfg) = 15
DEFAULT_REMOTE_PORT(/Users/jcuzella/src/pub/ansible-pause-bug-reproduction/ansible.cfg) = 22
DEFAULT_ROLES_PATH(/Users/jcuzella/src/pub/ansible-pause-bug-reproduction/ansible.cfg) = [u'/Users/jcuzella/src/pub/ansible-pause-bug-reproduction/roles']
DEFAULT_SUDO_EXE(/Users/jcuzella/src/pub/ansible-pause-bug-reproduction/ansible.cfg) = sudo
DEFAULT_SUDO_FLAGS(/Users/jcuzella/src/pub/ansible-pause-bug-reproduction/ansible.cfg) = -H
DEFAULT_SUDO_USER(/Users/jcuzella/src/pub/ansible-pause-bug-reproduction/ansible.cfg) = root
DEFAULT_TIMEOUT(/Users/jcuzella/src/pub/ansible-pause-bug-reproduction/ansible.cfg) = 60
DEFAULT_TRANSPORT(/Users/jcuzella/src/pub/ansible-pause-bug-reproduction/ansible.cfg) = smart
DEFAULT_VARS_PLUGIN_PATH(/Users/jcuzella/src/pub/ansible-pause-bug-reproduction/ansible.cfg) = [u'/usr/share/ansible_plugins/vars_plugins']
HOST_KEY_CHECKING(/Users/jcuzella/src/pub/ansible-pause-bug-reproduction/ansible.cfg) = False
```

##### OS / ENVIRONMENT

ansible running from CentOS 7 docker container (Reproduction steps & [test case repo][ansible-pause-bug-reproduction] provided!)

##### SUMMARY

As documented in the [`pause` module documentation][1], the module should accept a `Ctrl+c` input followed by either character: `a`, or `c` to abort or continue the playbook respectively:

> You can use `ctrl+c` if you wish to advance a pause earlier than it is set to expire or if you need to abort a playbook run entirely. To continue early press `ctrl+c` and then `c`. To abort a playbook press `ctrl+c` and then `a`.

Currently Ansible's `pause` module does not appear to accept `Ctrl+c` anymore, instead only pausing indefinitely (or until user forcibly kills the `ansible` process via another shell command), or accepting `Enter` to continue.  This is probably a behavior regression.  Only other related issue was #11386, but this was supposedly solved?

##### STEPS TO REPRODUCE

```

mkdir -p ~/src/pub/
cd ~/src/pub/
git clone git@github.com:trinitronx/ansible-pause-bug-reproduction.git
cd ansible-pause-bug-reproduction/
# Note: docker-run script assumes it is running somewhere under your $HOME dir!  This is for volume mounting playbook directory into docker container with the version of Ansible we can reproduce this on
./bin/docker-run 'ansible-playbook -i inventory/hosts playbooks/pause-test/pause-test.yml  -vvv --diff'
```

```yaml
---
# Bug reproduction to test Ctrl-c behavior on pause module
- name: Test pause module
  hosts: "localhost"
  become: no
  gather_facts: no
  tasks:
    - pause:
      prompt: "Uh-oh! Something doesn't look right... Press Ctlr-c to try and abort and hope for the best?"
      tags:
        - test_pause

    - debug: msg="I'm sorry Dave, I can't do that"
      tags:
        - test_pause
        - debug

    - name: We should never get here if you pressed Ctrl-c and aborted...
      debug: msg="Ooops, we didn't abort... now the playbook has done bad things even though you tried to stop it!"
      tags:
        - test_pause
        - debug

    - name: We should never get here if you pressed Ctrl-c and aborted...
      fail:
      tags:
        - test_pause
```

##### EXPECTED RESULTS

Ansible should have caught `Ctrl+c` input, and output the message:

`"Press 'C' to continue the play or 'A' to abort"`

Inputting `a` should have aborted the playbook run, and subsequent tasks should have never run.

##### ACTUAL RESULTS

Pause module never appears to catch `Ctrl+c` input and output the `"Press 'C' to continue the play or 'A' to abort"` message like it used to in older versions!  This could result in potentially bad behavior or consequences when playbook developers put in a `pause` task in order to have human intervention at some point in a playbook.  For example: to check some registered variables or state before continuing on with the rest of the playbook tasks.

If the user presses `Enter`, and is running with `-vvv` output, then the input characters are shown back to the user in `user_input`.  Clearly Ansible sees the input characters, but no longer acts on them.

- `Ctrl+c` is reported as `\u0003`, which is ["End of Text"][2]
- `Escape` is reported as `\u001b`, which is ["Escape"][3].

**Example playbook output**:
```
INFO: Found /tmp/ssh-C8ukortCdm/agent.23383
INFO: Running ssh forwarding pid: 15176
rm: cannot remove '/opt/ansible/ansible/lib/ansible.egg-info': Permission denied
no previously-included directories found matching 'ticket_stubs'
no previously-included directories found matching 'hacking'
warning: no files found matching 'SYMLINK_CACHE.json'
rm: cannot remove '/opt/ansible/ansible/lib/ansible.egg-info': Permission denied
running egg_info
writing requirements to lib/ansible.egg-info/requires.txt
writing lib/ansible.egg-info/PKG-INFO
writing top-level names to lib/ansible.egg-info/top_level.txt
writing dependency_links to lib/ansible.egg-info/dependency_links.txt
writing manifest file 'lib/ansible.egg-info/SOURCES.txt'
reading manifest file 'lib/ansible.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'ticket_stubs'
no previously-included directories found matching 'hacking'
warning: no files found matching 'SYMLINK_CACHE.json'
writing manifest file 'lib/ansible.egg-info/SOURCES.txt'

Setting up Ansible to run out of checkout...

PATH=/opt/ansible/ansible/bin:/opt/ansible/ansible/test/runner:/usr/local/opt/qt/bin:/Users/jcuzella/go/bin:/usr/local/bin:/opt/ansible/ansible/bin:/opt/ansible/ansible/test/runner:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin
PYTHONPATH=/opt/ansible/ansible/lib:
MANPATH=/opt/ansible/ansible/docs/man:

Remember, you may wish to specify your host file with -i

Done!

ansible-playbook 2.5.0 (devel 90f0c411e4) last updated 2018/01/20 04:59:06 (GMT +000)
  config file = /Users/jcuzella/src/pub/ansible-pause-bug-reproduction/ansible.cfg
  configured module search path = [u'/Users/jcuzella/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/ansible/ansible/lib/ansible
  executable location = /opt/ansible/ansible/bin/ansible-playbook
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
Using /Users/jcuzella/src/pub/ansible-pause-bug-reproduction/ansible.cfg as config file
[DEPRECATION WARNING]: DEFAULT_SUDO_FLAGS option, In favor of become which is a generic framework , use become instead. This feature will be removed in version 2.8. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: ANSIBLE_HOSTS option, The variable is misleading as it can be a list of hosts and/or paths to inventory sources , use ANSIBLE_INVENTORY instead. This feature will be removed in version 2.8. Deprecation warnings
can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: DEFAULT_SUDO_EXE option, In favor of become which is a generic framework , use become instead. This feature will be removed in version 2.8. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: DEFAULT_SUDO_USER option, In favor of become which is a generic framework , use become instead. This feature will be removed in version 2.8. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
Parsed /Users/jcuzella/src/pub/ansible-pause-bug-reproduction/inventory/hosts inventory source with ini plugin
 [WARNING]: Ignoring invalid attribute: prompt


PLAYBOOK: pause-test.yml *******************************************************************************************************************************************************************************************************************
1 plays in playbooks/pause-test/pause-test.yml

PLAY [Test pause module] *******************************************************************************************************************************************************************************************************************
META: ran handlers

TASK [pause] *******************************************************************************************************************************************************************************************************************************
task path: /Users/jcuzella/src/pub/ansible-pause-bug-reproduction/playbooks/pause-test/pause-test.yml:8
[pause]
Press enter to continue:
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^[^Caabort!
                                                                                                                                                                                             ok: [127.0.0.1] => {
    "attempts": 1,
    "changed": false,
    "delta": 9,
    "echo": true,
    "failed": false,
    "rc": 0,
    "start": "2018-01-25 17:46:40.211179",
    "stderr": "",
    "stdout": "Paused for 0.15 minutes",
    "stop": "2018-01-25 17:46:49.384308",
    "user_input": "\u0003\u0003\u0003\u0003\u0003\u0003\u0003\u0003\u0003\u0003\u0003\u0003\u0003\u0003\u0003\u0003\u0003\u0003\u0003\u0003\u0003\u0003\u0003\u0003\u0003\u0003\u0003\u0003\u0003\u0003\u0003\u0003\u0003\u0003\u0003\u0003\u0003\u0003\u0003\u0003\u0003\u0003\u0003\u0003\u0003\u0003\u0003\u0003\u0003\u0003\u0003\u0003\u0003\u0003\u0003\u0003\u0003\u0003\u001b\u001b\u001b\u001b\u001b\u001b\u001b\u001b\u001b\u001b\u001b\u001b\u001b\u001b\u001b\u001b\u001b\u001b\u001b\u001b\u001b\u001b\u001b\u001b\u001b\u001b\u001b\u001b\u001b\u001b\u001b\u001b\u0003aabort!"
}

TASK [debug] *******************************************************************************************************************************************************************************************************************************
task path: /Users/jcuzella/src/pub/ansible-pause-bug-reproduction/playbooks/pause-test/pause-test.yml:13
ok: [127.0.0.1] => {
    "attempts": 1,
    "failed": false,
    "msg": "I'm sorry Dave, I can't do that"
}

TASK [We should never get here if you pressed Ctrl-c and aborted...] ***********************************************************************************************************************************************************************
task path: /Users/jcuzella/src/pub/ansible-pause-bug-reproduction/playbooks/pause-test/pause-test.yml:18
ok: [127.0.0.1] => {
    "attempts": 1,
    "failed": false,
    "msg": "Ooops, we didn't abort... now the playbook has done bad things even though you tried to stop it!"
}

TASK [We should never get here if you pressed Ctrl-c and aborted...] ***********************************************************************************************************************************************************************
task path: /Users/jcuzella/src/pub/ansible-pause-bug-reproduction/playbooks/pause-test/pause-test.yml:24
fatal: [127.0.0.1]: FAILED! => {
    "attempts": 1,
    "changed": false,
    "failed": true,
    "msg": "Failed as requested from task"
}
	to retry, use: --limit @/Users/jcuzella/src/pub/ansible-pause-bug-reproduction/playbooks/pause-test/pause-test.retry

PLAY RECAP *********************************************************************************************************************************************************************************************************************************
127.0.0.1                  : ok=3    changed=0    unreachable=0    failed=1
```

[1]: http://docs.ansible.com/ansible/latest/pause_module.html
[2]: https://www.compart.com/en/unicode/U+0003
[3]: https://www.compart.com/en/unicode/U+001b
[ansible-pause-bug-reproduction]: https://github.com/trinitronx/ansible-pause-bug-reproduction

### PR DESCRIPTION
**Pull request by samdoran**
##### SUMMARY

Fixes #35372

Ctrl + C works in all scenarios.

Use `curses` to control stdout to avoid displaying control characters on screen and make interactive input more user friendly.

Validate the `echo` parameter and ensure it is always cast as a `bool`.

Add integration tests using `pexpect`.

Supercedes #38049 

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME
`pause.py`

##### ANSIBLE VERSION

```
2.6
```

### CODE REVIEW

File: test/integration/targets/pause/runme.sh [hunk 1]
```diff
@@ -0,0 +1,25 @@
+#!/usr/bin/env bash
+
+set -eux
+
+export ANSIBLE_ROLES_PATH=./roles
+
+python runme.py -i ../../inventory "$@"
```
Comment (mattclay) [inline test/integration/targets/pause/runme.sh]: You shouldn't need a `runme.sh` just to run `runme.py`, since ansible-test will execute `runme.py` directly.

Comment (mattclay) [reply test/integration/targets/pause/runme.sh]: However, to avoid having to install `pexpect` for every integration test run via `integration.txt`, it may be better to keep this for now and install `pexepect` via pip here rather than using `integration.txt`.

Comment (samdoran) [reply test/integration/targets/pause/runme.sh]: Thanks for answering that! I was going to ask you about that today but you beat me to it.

**Comment by samdoran** [comment]
@mattclay One thing I've noticed is that inside the container I don't have a tty to query for the appropriate `VERASE`. Would there be a way to add a tty to the container by running it with `-it` or `-t`?


```
Traceback (most recent call last):
  File "test-pause.py", line 17, in <module>
    backspace = termios.tcgetattr(sys.stdin.fileno())[6][termios.VERASE]
termios.error: (25, 'Inappropriate ioctl for device')
```

**Comment by mattclay** [comment]
@samdoran I'll try adding `-it` when running all test containers to see if it causes any issues.

**Comment by samdoran** [comment]
@mattclay I was able to work around that with a `try` `except` statement that hardcodes a backspace escape sequence and that seems to be working.

The last test problem I need to solve is that I am testing aborting the play interactively, which causes the tests to report failure (well, unstable actually). I thought I put the correct string in the task name, but that doesn't seem to fix it. This may be different than other tests in that I am actually aborting the play, but I'm not sure.

**Comment by mattclay** [comment]
@samdoran Your latest changes to use `EXPECTED FAILURE` should fix the unstable test results.

**Comment by mattclay** [comment]
It's good that you have a work around, because both `-it` and `-t` cause problems for CI.

**Comment by samdoran** [comment]
Thanks for looking into it.
