### PR TITLE
ansible-pull fix adhoc output inconsistencies on changed

### LINKED ISSUE #84863: ansible-pull --only-if-changed is broken
### Summary

When i use ansible-pull with ``--only-if-changed``, commit id changed, but modifications are not triggered.

```
[2025-03-19 20:21:18] 4a-k1-12d.domain.com | CHANGED => 
[2025-03-19 20:21:18]     after: 5db3493a82a58ef28ac5521778cb35e8dd97d5ca
[2025-03-19 20:21:18]     ansible_facts:
[2025-03-19 20:21:18]         discovered_interpreter_python: /usr/bin/python3.11
[2025-03-19 20:21:18]     before: 5dd538dfe19c6991fccc8cf675e99e68891fde24
[2025-03-19 20:21:18]     changed: true
[2025-03-19 20:21:18]     remote_url_changed: false
[2025-03-19 20:21:18] Repository has not changed, quitting.
```

### Issue Type

Bug Report

### Component Name

ansible-pull

### Ansible Version

```console
$ ansible --version
ansible [core 2.18.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/ansible/lib/python3.11/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/ansible/bin/ansible
  python version = 3.11.2 (main, Nov 30 2024, 21:22:50) [GCC 12.2.0] (/opt/ansible/bin/python3)
  jinja version = 3.1.5
  libyaml = True
```

### Configuration

```console
# if using a version older than ansible-core 2.12 you should omit the '-t all'
$ ansible-config dump --only-changed -t all
ANSIBLE_FORCE_COLOR(/etc/ansible/ansible.cfg) = True
CONFIG_FILE() = /etc/ansible/ansible.cfg
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = explicit
DEFAULT_REMOTE_USER(/etc/ansible/ansible.cfg) = root
DEFAULT_VERBOSITY(/etc/ansible/ansible.cfg) = 0
DISPLAY_SKIPPED_HOSTS(/etc/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/etc/ansible/ansible.cfg) = auto_silent
PAGER(env: PAGER) = most
SHOW_CUSTOM_STATS(/etc/ansible/ansible.cfg) = True

GALAXY_SERVERS:


CALLBACK:
========

default:
_______
display_failed_stderr(/etc/ansible/ansible.cfg) = True
display_skipped_hosts(/etc/ansible/ansible.cfg) = False
result_format(/etc/ansible/ansible.cfg) = yaml
show_custom_stats(/etc/ansible/ansible.cfg) = True

minimal:
_______
result_format(/etc/ansible/ansible.cfg) = yaml

CONNECTION:
==========

paramiko_ssh:
____________
remote_user(/etc/ansible/ansible.cfg) = root

ssh:
___
remote_user(/etc/ansible/ansible.cfg) = root
```

### OS / Environment

Debian 12

### Steps to Reproduce

Commit to the ansible repository
Run ansible-pull

### Expected Results

Playbook to be played

### Actual Results

```console
``Repository has not changed``
```

### Code of Conduct

- [x] I agree to follow the Ansible Code of Conduct

### PR DESCRIPTION
**Pull request by bcoca**
Remove changes to adhoc output that could throw off change detection on ansible pull

fixes #84863

##### ISSUE TYPE

- Bugfix Pull Request

### CODE REVIEW

**Comment by bcoca** [comment]
[eoli3n](https://github.com/eoli3n) can you confirm this fixes your issue (sans workaround)?

File: test/integration/targets/ansible-pull/runme.sh [hunk 1]
```diff
@@ -27,6 +27,23 @@ cd "${repo_dir}"
     git commit -m "Initial commit."
 )
 
+function change_repo {
+	cd "${repo_dir}"
+	date > forced_change
+	git add forced_change
+	git commit -m "forced changed"
+	cd -
```
Comment (Akasurde) [inline test/integration/targets/ansible-pull/runme.sh]:
```suggestion
    cd "${repo_dir}"
    date > forced_change
    git add forced_change
    git commit -m "forced changed"
    cd -
```

File: test/integration/targets/ansible-pull/runme.sh [hunk 2]
```diff
@@ -27,6 +27,23 @@ cd "${repo_dir}"
...
+}
+
+function no_change_tests {
+	# test for https://github.com/ansible/ansible/issues/13688
+	if grep MAGICKEYWORD "${temp_log}"; then
+	    cat "${temp_log}"
+	    echo "Ran the playbook, found MAGICKEYWORD in output."
+	    exit 1
+	fi
```
Comment (Akasurde) [inline test/integration/targets/ansible-pull/runme.sh]:
```suggestion
    # test for https://github.com/ansible/ansible/issues/13688
    if grep MAGICKEYWORD "${temp_log}"; then
        cat "${temp_log}"
        echo "Ran the playbook, found MAGICKEYWORD in output."
        exit 1
    fi
```

**Review by Akasurde — CHANGES_REQUESTED** [review]

File: lib/ansible/cli/pull.py [hunk 3]
```diff
@@ -347,7 +379,7 @@ def select_playbook(path):
             if 0 < len(errors):
                 display.warning("\n".join(errors))
             elif len(playbooks) == len(context.CLIARGS['args']):
-                playbook = " ".join(playbooks)
+                playbook = " ".join(str(playbooks))
```
Comment (a-holm) [inline lib/ansible/cli/pull.py]: the change from `" ".join(playbooks)` to `" ".join(str(playbooks))` in the `select_playbook` method looks like it might be incorrect. `str(playbooks)` would stringify the list itself, rather than joining the path strings within it. Was this intended? It seems like it should revert to `" ".join(playbooks)`.

File: changelogs/fragments/pull_changed_fix.yml [hunk 4]
```diff
@@ -0,0 +1,2 @@
+bugfixes:
+  - ansible-pull change detection will now work independant of callback or result format settings.
```
Comment (Akasurde) [inline changelogs/fragments/pull_changed_fix.yml]:
```suggestion
  - ansible-pull change detection will now work independently of callback or result format settings.
```

**Review by Akasurde — APPROVED** [review]
